[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name = "criticalflow"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
  "numpy>=2.4.4",
  "openai>=2.30.0",
  "pydantic>=2.12.5",
  "python-dotenv>=1.2.2",
  "sqlmodel>=0.0.37",
]

[tool.maturin]
manifest-path = "crates/graph_engine/Cargo.toml"
features = ["python"]
